tenant: demo # Enter your tenant name here
app: serverless-test # Enter your application name here
service: demo-crud

frameworkVersion: ">=1.38.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x

functions:
  createUser:
    handler: src/users.createUser
    events:
      - http:
          path: user
          method: post
          cors: true
  getUsers:
    handler: src/users.getUsers
    events:
      - http:
          path: user
          method: get
          cors: true
  updateUser:
    handler: src/users.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true
  deleteUser:
    handler: src/users.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true
plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
